### ISSUE TITLE
what about we move to Makefile?

### ISSUE THREAD

**Issue by mfrasca** [ppinter1/nonpareil#1]
or any other mainstream build tool, that is still maintained.
the current `scons` configuration runs fine only the 'install' task: on my Debian machine 'build' tries to compile for Windows, too, which is not what I wish to do.
running 'install' goes fine if you trust the script, and you do it as `root`, or you need tamper with the `scons` configuration, and understand how to install somewhere where your user has write privileges.
we could fix these issues, but what about we move to Makefile, that would also be helpful when porting to other systems, where scons is not available.

**Comment by ppinter1** [comment]
I looked at doing this once and went cross-eyed trying to understand scons.

The complexity of build systems baffles me (I don't get the point of gradle at all).

I'll probably just keep the executable file around to use on my Debian based systems.

But, feel free to fork the project and add your work to solve the problem.

If you do, you have more skill and patience than I do.

buona fortuna a te

**Comment by mfrasca** [comment]
I have forked the project, I didn't also want to keep a separate issues area, this is why I opened the issue here.  if you reopen the issue, I will remember I wanted to have a look at it. :wink:

**Comment by mfrasca** [comment]
actually, this is not just "let's move away from scons", it's more "let's make sure you can build the program as documented" and "please don't require people running stuff as administrator".
but scons is a problem to me on the system I'm using (MeeGo), where I'm afraid it is not available.

**Comment by mfrasca** [comment]
813e94a
