### ISSUE TITLE
update scons configuration

### ISSUE THREAD

**Issue by mfrasca** [ppinter1/nonpareil#2]
there are several warnings about deprecated classes:

    scons: warning: The Options class is deprecated; use the Variables class instead.
    scons: warning: The EnumOption() function is deprecated; use the EnumVariable() function instead.
    scons: warning: The PathOption() function is deprecated; use the PathVariable() function instead.
    scons: warning: The BoolOption() function is deprecated; use the BoolVariable() function instead.
    scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.

**Comment by mfrasca** [comment]
67bfebc50231d2a6c237fd449e6dc34bcb1a59a4

**Comment by ppinter1** [comment]
Grazie mille, Mario!
